workflows:
  hello-world:
    name: Hello world workflow
    scripts:
        - echo "Hello World!"
  build-android:
    scripts:
      - name: Build Android APK
        working_directory: android
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
  my-workflow:
    publishing:
      email:
        recipients:
          - ewerton.ricardo98@gmail.com